# general configuration
url: https://haruyuki.moe
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/logo.jpg"
  # author will appear under the avatar (optional)
  author: "Haruyuki"
  # tagline will appear under the title (optional)
  tagline: "(>Ï‰<)"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "BluMewMew"
  description: "I love to code Discord bots as a hobby, nice to meet you!"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
